---
alerts: &alerts
  on_success:
    put: slack
    params:
      alert_type: fixed
      disable: ((disable_alerts))
  on_failure:
    put: slack
    params:
      alert_type: broke
      disable: ((disable_alerts))
  on_error:
    put: slack
    params:
      alert_type: broke
      color: "#F5A623"
      disable: ((disable_alerts))

resource_types:
- name: slack-alert
  type: registry-image
  source: {repository: arbourd/concourse-slack-alert-resource}

resources:
- name: new-starters
  type: git
  webhook_token: ((webhook_token))
  source:
    uri: https://github.com/EngineerBetter/new-starters.git
    branch: main
- name: slack
  type: slack-alert
  source:
    url: ((slack_webhook))
    channel: '#integrations'
    username: admin
    password: ((concourse_password))
- name: every-1h
  type: time
  source: {interval: 2m}

jobs:
- name: set-pipeline
  <<: *alerts
  plan:
  - get: new-starters
    trigger: true
  - get: every-1h
    trigger: true
  - set_pipeline: self
    file: new-starters/ci/pipeline.yml

- name: create-icebox
  serial: true
  <<: *alerts
  plan:
  - get: new-starters
    trigger: true
    passed: [set-pipeline]
  - get: every-1h
    trigger: true
    passed: [set-pipeline]
  - in_parallel:
    - task: delete-stories
      file: new-starters/ci/delete-stories.yml
      params:
        TRACKER_PROJECT_ID: &tracker_project_id "2530961"
        TRACKER_TOKEN: ((tracker_token))
    - do:
      - task: generate-csvs
        file: new-starters/ci/generate-tracker-csvs.yml
      - task: convert-csvs
        file: new-starters/ci/convert-csv-to-json.yml
  - task: create-stories
    file: new-starters/ci/create-stories.yml
    params:
      TRACKER_PROJECT_ID: *tracker_project_id
      TRACKER_TOKEN: ((tracker_token))